FROM ubuntu:focal

# Install Dependencies
RUN set -eux; \
    apt-get update && apt-get install -y \
    zsh \
    gnupg2 \
    gosu \
    git \
    && rm -rf /var/lib/apt/lists/*

# Non-root user ARGs
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --shell /bin/zsh --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && chown -R $USERNAME /home/${USERNAME}

# Use non-root user
USER $USERNAME
